# This file was generated by GoReleaser. DO NOT EDIT.
cask "osp-release" do
  artifact ".claude/skills/osp-release/SKILL.md",
    target: "#{Dir.home}/.claude/skills/osp-release/SKILL.md"

  version "0.3.0"

  on_macos do
    on_arm do
      sha256 "8e6d5ede170fc0101ac6c34c5bfb78edf1b8e9ec34bcb0bda94b109982a32017"
      url "https://github.com/openshift-pipelines/osp-release/releases/download/v#{version}/osp-release_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/openshift-pipelines/osp-release/"
    end
    on_intel do
      sha256 "930f8b60d70c9f88bc2ce6e75df2a068b14bf43c10b9b06b12a93db801013284"
      url "https://github.com/openshift-pipelines/osp-release/releases/download/v#{version}/osp-release_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/openshift-pipelines/osp-release/"
    end
  end
  on_linux do
    on_arm do
      sha256 "f3bcb5bde0dc2e03691d58e7d00f310554e6f3b239933869dbb654bfc5abbc66"
      url "https://github.com/openshift-pipelines/osp-release/releases/download/v#{version}/osp-release_#{version}_linux_arm64.tar.gz",
        verified: "github.com/openshift-pipelines/osp-release/"
    end
    on_intel do
      sha256 "3f1383a58e06e112a9f3079880cb681ad30b3255fdbcfbbeb6c219bfa75d5c84"
      url "https://github.com/openshift-pipelines/osp-release/releases/download/v#{version}/osp-release_#{version}_linux_amd64.tar.gz",
        verified: "github.com/openshift-pipelines/osp-release/"
    end
  end

  name "osp-release"
  desc "Query OpenShift Pipelines release data from Confluence, Jira, and GitHub"
  homepage "https://github.com/openshift-pipelines/osp-release"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "osp-release"

  # No zap stanza required

  caveats <<~EOS
    If macOS blocks the binary after install, run:
      xattr -dr com.apple.quarantine "$(which osp-release)"
  EOS
end
