# This file was generated by GoReleaser. DO NOT EDIT.
cask "osp-release" do
  name "osp-release"
  desc "Query OpenShift Pipelines release data from Confluence, Jira, and GitHub"
  homepage "https://github.com/openshift-pipelines/osp-release"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "osp-release"

  on_macos do
    on_intel do
      url "https://github.com/openshift-pipelines/osp-release/releases/download/v#{version}/osp-release_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/openshift-pipelines/osp-release/"
      sha256 "07ddf1ad1b134b8dd94d904da6ea3174ecf65d47c36f37e87e1dde5ce25d2124"
    end
    on_arm do
      url "https://github.com/openshift-pipelines/osp-release/releases/download/v#{version}/osp-release_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/openshift-pipelines/osp-release/"
      sha256 "59f73fd52c4f111578d617bd317b421d7021a69b49b1dd47e51670ee9b82b09e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/openshift-pipelines/osp-release/releases/download/v#{version}/osp-release_#{version}_linux_amd64.tar.gz",
        verified: "github.com/openshift-pipelines/osp-release/"
      sha256 "c10de3b71177b4bd899bfe2845b9519c1412868a051af449296e7e7b8b7ee211"
    end
    on_arm do
      url "https://github.com/openshift-pipelines/osp-release/releases/download/v#{version}/osp-release_#{version}_linux_arm64.tar.gz",
        verified: "github.com/openshift-pipelines/osp-release/"
      sha256 "c0a0b255933cedd5c58d9c7ad1639060dff3cd5bf6f3c513ac703008d93e8e44"
    end
  end

  caveats do
    "If macOS blocks the binary after install, run:"
    "  xattr -dr com.apple.quarantine "$(which osp-release)""
  end

  # No zap stanza required
end
