# This file was generated by GoReleaser. DO NOT EDIT.
cask "osp-release" do
  name "osp-release"
  desc "Query OpenShift Pipelines release data from Confluence, Jira, and GitHub"
  homepage "https://github.com/openshift-pipelines/osp-release"
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "osp-release"

  on_macos do
    on_intel do
      url "https://github.com/openshift-pipelines/osp-release/releases/download/v#{version}/osp-release_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/openshift-pipelines/osp-release/"
      sha256 "330b5696a7b45419d56e2258f60fbd0ba49eed8cea39daaf9aa0bdc05561121a"
    end
    on_arm do
      url "https://github.com/openshift-pipelines/osp-release/releases/download/v#{version}/osp-release_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/openshift-pipelines/osp-release/"
      sha256 "0a287380997f7a1097ae0d852022a044ab2d5bedae9da1571de0beabeb2b1972"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/openshift-pipelines/osp-release/releases/download/v#{version}/osp-release_#{version}_linux_amd64.tar.gz",
        verified: "github.com/openshift-pipelines/osp-release/"
      sha256 "abd15668874bf90a3654841607ef8a3c807022e38cf45bdea4c84709042116ce"
    end
    on_arm do
      url "https://github.com/openshift-pipelines/osp-release/releases/download/v#{version}/osp-release_#{version}_linux_arm64.tar.gz",
        verified: "github.com/openshift-pipelines/osp-release/"
      sha256 "a69935c0e9b18263acb45fcf6820b89ec8d4a4ee68b26675b6609f5aba2757fe"
    end
  end

  caveats do
    "If macOS blocks the binary after install, run:"
    "  xattr -dr com.apple.quarantine "$(which osp-release)""
  end

  # No zap stanza required
end
